version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001" # Adjust this if your server listens on a different port
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"
      - "15672:15672"
